import { StyleSheet } from "react-native";
import { colors } from "../colors";

export const styles = StyleSheet.create({
  container: { paddingHorizontal: 12, marginVertical: 8 },
  label: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.title,
    marginBottom: 8,
    letterSpacing: 0.3,
  },
  input: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 2,
    borderColor: colors.border,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: colors.card,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 1,
  },
  inputActive: {
    borderColor: colors.button,
    backgroundColor: colors.bg,
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 2,
  },
  inputText: {
    flex: 1,
    color: colors.text,
    fontSize: 15,
    fontWeight: "600",
  },
  placeholder: {
    color: colors.placeholder,
  },
  dropdown: {
    marginTop: 8,
    maxHeight: 400,
    borderWidth: 2,
    borderColor: colors.border,
    borderRadius: 16,
    backgroundColor: colors.card,
    overflow: "hidden",
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 8,
  },
  section: {
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: colors.bg,
  },
  sectionTitle: {
    fontWeight: "600",
    color: colors.title,
    fontSize: 15,
    letterSpacing: 0.3,
  },
  sectionTitleActive: {
    color: colors.title,
  },
  roomsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: 8,
    paddingVertical: 8,
    gap: 8,
  },
  roomItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: colors.border,
    backgroundColor: colors.bg,
    width: "48%",
  },
  roomItemActive: {
    backgroundColor: colors.button,
    borderColor: colors.button,
  },
  roomText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: "500",
    letterSpacing: 0.2,
    flex: 1,
  },
  roomTextActive: {
    color: "white",
    fontWeight: "600",
  },
});
