import { StyleSheet } from "react-native";
import { colors } from "../colors";

export const styles = StyleSheet.create({
  container: { paddingHorizontal: 12, marginVertical: 8 },
  label: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.title,
    marginBottom: 8,
    letterSpacing: 0.3,
  },
  input: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 2,
    borderColor: colors.border,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: colors.card,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 1,
  },
  inputActive: {
    borderColor: colors.button,
    backgroundColor: colors.bg,
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 2,
  },
  inputText: {
    flex: 1,
    color: colors.text,
    fontSize: 15,
    fontWeight: "500",
    letterSpacing: 0.2,
  },
  placeholder: {
    color: colors.placeholder,
  },
  dropdown: {
    marginTop: 8,
    borderWidth: 2,
    borderColor: colors.border,
    borderRadius: 16,
    backgroundColor: colors.card,
    overflow: "hidden",
    zIndex: 1000,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 8,
  },
  option: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  optionActive: {
    backgroundColor: colors.bg,
  },
  optionText: {
    color: colors.text,
    fontSize: 15,
    fontWeight: "500",
    letterSpacing: 0.2,
  },
  optionTextActive: {
    color: colors.title,
    fontWeight: "600",
  },
});
